[general]


[watched_folders]
input = "/Users/jli8/Desktop" # name of input_folder

[output_folders]
target = "/Users/jli8/Pictures/screenshots" # name of output_folder, working files


[watcher_settings]
file_suffix = "png"
regex_compile_string = "Screenshot.+.png"







